// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: login_secret.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LoginSecretServiceClient is the client API for LoginSecretService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginSecretServiceClient interface {
	CreateLoginSecret(ctx context.Context, in *CreateLoginSecretRequest, opts ...grpc.CallOption) (*SecretSecretResponse, error)
	UpdateLoginSecret(ctx context.Context, in *UpdateLoginSecretRequest, opts ...grpc.CallOption) (*SecretSecretResponse, error)
	DeleteLoginSecret(ctx context.Context, in *DeleteLoginSecretRequest, opts ...grpc.CallOption) (*SecretSecretResponse, error)
}

type loginSecretServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginSecretServiceClient(cc grpc.ClientConnInterface) LoginSecretServiceClient {
	return &loginSecretServiceClient{cc}
}

func (c *loginSecretServiceClient) CreateLoginSecret(ctx context.Context, in *CreateLoginSecretRequest, opts ...grpc.CallOption) (*SecretSecretResponse, error) {
	out := new(SecretSecretResponse)
	err := c.cc.Invoke(ctx, "/proto.LoginSecretService/CreateLoginSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginSecretServiceClient) UpdateLoginSecret(ctx context.Context, in *UpdateLoginSecretRequest, opts ...grpc.CallOption) (*SecretSecretResponse, error) {
	out := new(SecretSecretResponse)
	err := c.cc.Invoke(ctx, "/proto.LoginSecretService/UpdateLoginSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginSecretServiceClient) DeleteLoginSecret(ctx context.Context, in *DeleteLoginSecretRequest, opts ...grpc.CallOption) (*SecretSecretResponse, error) {
	out := new(SecretSecretResponse)
	err := c.cc.Invoke(ctx, "/proto.LoginSecretService/DeleteLoginSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginSecretServiceServer is the server API for LoginSecretService service.
// All implementations must embed UnimplementedLoginSecretServiceServer
// for forward compatibility
type LoginSecretServiceServer interface {
	CreateLoginSecret(context.Context, *CreateLoginSecretRequest) (*SecretSecretResponse, error)
	UpdateLoginSecret(context.Context, *UpdateLoginSecretRequest) (*SecretSecretResponse, error)
	DeleteLoginSecret(context.Context, *DeleteLoginSecretRequest) (*SecretSecretResponse, error)
	mustEmbedUnimplementedLoginSecretServiceServer()
}

// UnimplementedLoginSecretServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLoginSecretServiceServer struct {
}

func (UnimplementedLoginSecretServiceServer) CreateLoginSecret(context.Context, *CreateLoginSecretRequest) (*SecretSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLoginSecret not implemented")
}
func (UnimplementedLoginSecretServiceServer) UpdateLoginSecret(context.Context, *UpdateLoginSecretRequest) (*SecretSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLoginSecret not implemented")
}
func (UnimplementedLoginSecretServiceServer) DeleteLoginSecret(context.Context, *DeleteLoginSecretRequest) (*SecretSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLoginSecret not implemented")
}
func (UnimplementedLoginSecretServiceServer) mustEmbedUnimplementedLoginSecretServiceServer() {}

// UnsafeLoginSecretServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginSecretServiceServer will
// result in compilation errors.
type UnsafeLoginSecretServiceServer interface {
	mustEmbedUnimplementedLoginSecretServiceServer()
}

func RegisterLoginSecretServiceServer(s grpc.ServiceRegistrar, srv LoginSecretServiceServer) {
	s.RegisterService(&LoginSecretService_ServiceDesc, srv)
}

func _LoginSecretService_CreateLoginSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLoginSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginSecretServiceServer).CreateLoginSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LoginSecretService/CreateLoginSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginSecretServiceServer).CreateLoginSecret(ctx, req.(*CreateLoginSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginSecretService_UpdateLoginSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLoginSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginSecretServiceServer).UpdateLoginSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LoginSecretService/UpdateLoginSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginSecretServiceServer).UpdateLoginSecret(ctx, req.(*UpdateLoginSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginSecretService_DeleteLoginSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLoginSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginSecretServiceServer).DeleteLoginSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LoginSecretService/DeleteLoginSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginSecretServiceServer).DeleteLoginSecret(ctx, req.(*DeleteLoginSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginSecretService_ServiceDesc is the grpc.ServiceDesc for LoginSecretService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginSecretService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LoginSecretService",
	HandlerType: (*LoginSecretServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLoginSecret",
			Handler:    _LoginSecretService_CreateLoginSecret_Handler,
		},
		{
			MethodName: "UpdateLoginSecret",
			Handler:    _LoginSecretService_UpdateLoginSecret_Handler,
		},
		{
			MethodName: "DeleteLoginSecret",
			Handler:    _LoginSecretService_DeleteLoginSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login_secret.proto",
}
