version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=homestead
      - POSTGRES_USER=homestead
      - POSTGRES_PASSWORD=homestead
    ports:
      - "54321:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
